### PR TITLE
refactored endpoint folder structure

### PR DESCRIPTION
**Pull request by AlexTeusz**
This change refactores the folder `endpoint` in order to provide a better understanding and a clearer view.

### CODE REVIEW

**Comment by AlexTeusz** [comment]
@cabullmann could you please validate this? Thanks :)

**Review by cabullmann — COMMENTED** [review]
Where is the realtime translation Transformer?

**Comment by AlexTeusz** [comment]
@cabullmann the realtime translation transformer is now in `webchat/translate`

**Review by cabullmann — APPROVED** [review]

**Comment by cabullmann** [comment]
Feel free to merge

**Pull request merged**
